package com.wincom.mstar.domain;

import java.util.Date;

public class AHistoryDataMinute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.DatId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer datid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.MachRoomId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer machroomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.Type
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.EnergyType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer energytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.CurrentValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Double currentvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.RecordTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date recordtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.MaxValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Double maxvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.MaxOccuredTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date maxoccuredtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.MinValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Double minvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.MinOccuredTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date minoccuredtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.AHistoryDataMinute.AverageValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Double averagevalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.DatId
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.DatId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDatid() {
        return datid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.DatId
     *
     * @param datid the value for Energy.dbo.AHistoryDataMinute.DatId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDatid(Integer datid) {
        this.datid = datid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.MachRoomId
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.MachRoomId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getMachroomid() {
        return machroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.MachRoomId
     *
     * @param machroomid the value for Energy.dbo.AHistoryDataMinute.MachRoomId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMachroomid(Integer machroomid) {
        this.machroomid = machroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.Type
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.Type
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.Type
     *
     * @param type the value for Energy.dbo.AHistoryDataMinute.Type
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.EnergyType
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.EnergyType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getEnergytype() {
        return energytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.EnergyType
     *
     * @param energytype the value for Energy.dbo.AHistoryDataMinute.EnergyType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setEnergytype(Integer energytype) {
        this.energytype = energytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.CurrentValue
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.CurrentValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Double getCurrentvalue() {
        return currentvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.CurrentValue
     *
     * @param currentvalue the value for Energy.dbo.AHistoryDataMinute.CurrentValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setCurrentvalue(Double currentvalue) {
        this.currentvalue = currentvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.RecordTime
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.RecordTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.RecordTime
     *
     * @param recordtime the value for Energy.dbo.AHistoryDataMinute.RecordTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.MaxValue
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.MaxValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Double getMaxvalue() {
        return maxvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.MaxValue
     *
     * @param maxvalue the value for Energy.dbo.AHistoryDataMinute.MaxValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMaxvalue(Double maxvalue) {
        this.maxvalue = maxvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.MaxOccuredTime
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.MaxOccuredTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getMaxoccuredtime() {
        return maxoccuredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.MaxOccuredTime
     *
     * @param maxoccuredtime the value for Energy.dbo.AHistoryDataMinute.MaxOccuredTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMaxoccuredtime(Date maxoccuredtime) {
        this.maxoccuredtime = maxoccuredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.MinValue
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.MinValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Double getMinvalue() {
        return minvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.MinValue
     *
     * @param minvalue the value for Energy.dbo.AHistoryDataMinute.MinValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMinvalue(Double minvalue) {
        this.minvalue = minvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.MinOccuredTime
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.MinOccuredTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getMinoccuredtime() {
        return minoccuredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.MinOccuredTime
     *
     * @param minoccuredtime the value for Energy.dbo.AHistoryDataMinute.MinOccuredTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMinoccuredtime(Date minoccuredtime) {
        this.minoccuredtime = minoccuredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.AHistoryDataMinute.AverageValue
     *
     * @return the value of Energy.dbo.AHistoryDataMinute.AverageValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Double getAveragevalue() {
        return averagevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.AHistoryDataMinute.AverageValue
     *
     * @param averagevalue the value for Energy.dbo.AHistoryDataMinute.AverageValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAveragevalue(Double averagevalue) {
        this.averagevalue = averagevalue;
    }
}