package com.wincom.mstar.domain;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.Area.AreaId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.Area.Type
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.Area.AreaType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer areatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.Area.AreaName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.Area.ParAreaId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer parareaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Energy.dbo.Area.ParAreaId1
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer parareaid1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.Area.AreaId
     *
     * @return the value of Energy.dbo.Area.AreaId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.Area.AreaId
     *
     * @param areaid the value for Energy.dbo.Area.AreaId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.Area.Type
     *
     * @return the value of Energy.dbo.Area.Type
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.Area.Type
     *
     * @param type the value for Energy.dbo.Area.Type
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.Area.AreaType
     *
     * @return the value of Energy.dbo.Area.AreaType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getAreatype() {
        return areatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.Area.AreaType
     *
     * @param areatype the value for Energy.dbo.Area.AreaType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAreatype(Integer areatype) {
        this.areatype = areatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.Area.AreaName
     *
     * @return the value of Energy.dbo.Area.AreaName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.Area.AreaName
     *
     * @param areaname the value for Energy.dbo.Area.AreaName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.Area.ParAreaId
     *
     * @return the value of Energy.dbo.Area.ParAreaId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getParareaid() {
        return parareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.Area.ParAreaId
     *
     * @param parareaid the value for Energy.dbo.Area.ParAreaId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setParareaid(Integer parareaid) {
        this.parareaid = parareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Energy.dbo.Area.ParAreaId1
     *
     * @return the value of Energy.dbo.Area.ParAreaId1
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getParareaid1() {
        return parareaid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Energy.dbo.Area.ParAreaId1
     *
     * @param parareaid1 the value for Energy.dbo.Area.ParAreaId1
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setParareaid1(Integer parareaid1) {
        this.parareaid1 = parareaid1;
    }
}