package com.wincom.mstar.domain;

import java.util.Date;

public class BDIHistoryQuarter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.DataObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer dataobjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.RecordTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date recordtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.CurrentValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer currentvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.CurrentStr
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String currentstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.EventCount
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer eventcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.YearNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer yearno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.MonthNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer monthno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.DayNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer dayno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.HourNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer hourno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BDIHistoryQuarter.QuarterNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer quarterno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.DataObjID
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.DataObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDataobjid() {
        return dataobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.DataObjID
     *
     * @param dataobjid the value for nfjd502.dbo.BDIHistoryQuarter.DataObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDataobjid(Integer dataobjid) {
        this.dataobjid = dataobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.RecordTime
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.RecordTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.RecordTime
     *
     * @param recordtime the value for nfjd502.dbo.BDIHistoryQuarter.RecordTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.CurrentValue
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.CurrentValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getCurrentvalue() {
        return currentvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.CurrentValue
     *
     * @param currentvalue the value for nfjd502.dbo.BDIHistoryQuarter.CurrentValue
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setCurrentvalue(Integer currentvalue) {
        this.currentvalue = currentvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.CurrentStr
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.CurrentStr
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getCurrentstr() {
        return currentstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.CurrentStr
     *
     * @param currentstr the value for nfjd502.dbo.BDIHistoryQuarter.CurrentStr
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setCurrentstr(String currentstr) {
        this.currentstr = currentstr == null ? null : currentstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.EventCount
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.EventCount
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getEventcount() {
        return eventcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.EventCount
     *
     * @param eventcount the value for nfjd502.dbo.BDIHistoryQuarter.EventCount
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setEventcount(Integer eventcount) {
        this.eventcount = eventcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.YearNo
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.YearNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getYearno() {
        return yearno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.YearNo
     *
     * @param yearno the value for nfjd502.dbo.BDIHistoryQuarter.YearNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setYearno(Integer yearno) {
        this.yearno = yearno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.MonthNo
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.MonthNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getMonthno() {
        return monthno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.MonthNo
     *
     * @param monthno the value for nfjd502.dbo.BDIHistoryQuarter.MonthNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMonthno(Integer monthno) {
        this.monthno = monthno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.DayNo
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.DayNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDayno() {
        return dayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.DayNo
     *
     * @param dayno the value for nfjd502.dbo.BDIHistoryQuarter.DayNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDayno(Integer dayno) {
        this.dayno = dayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.HourNo
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.HourNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getHourno() {
        return hourno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.HourNo
     *
     * @param hourno the value for nfjd502.dbo.BDIHistoryQuarter.HourNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setHourno(Integer hourno) {
        this.hourno = hourno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BDIHistoryQuarter.QuarterNo
     *
     * @return the value of nfjd502.dbo.BDIHistoryQuarter.QuarterNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getQuarterno() {
        return quarterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BDIHistoryQuarter.QuarterNo
     *
     * @param quarterno the value for nfjd502.dbo.BDIHistoryQuarter.QuarterNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setQuarterno(Integer quarterno) {
        this.quarterno = quarterno;
    }
}