package com.wincom.mstar.domain;

import java.util.Date;

public class BOperationData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOperationData.OperationIndex
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer operationindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOperationData.OperationID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer operationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOperationData.Position
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOperationData.OperationName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String operationname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOperationData.OperateTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date operatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOperationData.OperationEndTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date operationendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOperationData.OperationResult
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String operationresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOperationData.OperationLogID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer operationlogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOperationData.UserId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOperationData.OperationIndex
     *
     * @return the value of nfjd502.dbo.BOperationData.OperationIndex
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getOperationindex() {
        return operationindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOperationData.OperationIndex
     *
     * @param operationindex the value for nfjd502.dbo.BOperationData.OperationIndex
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setOperationindex(Integer operationindex) {
        this.operationindex = operationindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOperationData.OperationID
     *
     * @return the value of nfjd502.dbo.BOperationData.OperationID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getOperationid() {
        return operationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOperationData.OperationID
     *
     * @param operationid the value for nfjd502.dbo.BOperationData.OperationID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setOperationid(Integer operationid) {
        this.operationid = operationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOperationData.Position
     *
     * @return the value of nfjd502.dbo.BOperationData.Position
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOperationData.Position
     *
     * @param position the value for nfjd502.dbo.BOperationData.Position
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOperationData.OperationName
     *
     * @return the value of nfjd502.dbo.BOperationData.OperationName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getOperationname() {
        return operationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOperationData.OperationName
     *
     * @param operationname the value for nfjd502.dbo.BOperationData.OperationName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setOperationname(String operationname) {
        this.operationname = operationname == null ? null : operationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOperationData.OperateTime
     *
     * @return the value of nfjd502.dbo.BOperationData.OperateTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOperationData.OperateTime
     *
     * @param operatetime the value for nfjd502.dbo.BOperationData.OperateTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOperationData.OperationEndTime
     *
     * @return the value of nfjd502.dbo.BOperationData.OperationEndTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getOperationendtime() {
        return operationendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOperationData.OperationEndTime
     *
     * @param operationendtime the value for nfjd502.dbo.BOperationData.OperationEndTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setOperationendtime(Date operationendtime) {
        this.operationendtime = operationendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOperationData.OperationResult
     *
     * @return the value of nfjd502.dbo.BOperationData.OperationResult
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getOperationresult() {
        return operationresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOperationData.OperationResult
     *
     * @param operationresult the value for nfjd502.dbo.BOperationData.OperationResult
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setOperationresult(String operationresult) {
        this.operationresult = operationresult == null ? null : operationresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOperationData.OperationLogID
     *
     * @return the value of nfjd502.dbo.BOperationData.OperationLogID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getOperationlogid() {
        return operationlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOperationData.OperationLogID
     *
     * @param operationlogid the value for nfjd502.dbo.BOperationData.OperationLogID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setOperationlogid(Integer operationlogid) {
        this.operationlogid = operationlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOperationData.UserId
     *
     * @return the value of nfjd502.dbo.BOperationData.UserId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOperationData.UserId
     *
     * @param userid the value for nfjd502.dbo.BOperationData.UserId
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}