package com.wincom.mstar.domain;

import java.util.Date;

public class BOptimalEvent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOptimalEvent.EventID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer eventid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOptimalEvent.ObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer objid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOptimalEvent.StartTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.BOptimalEvent.EndTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOptimalEvent.EventID
     *
     * @return the value of nfjd502.dbo.BOptimalEvent.EventID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getEventid() {
        return eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOptimalEvent.EventID
     *
     * @param eventid the value for nfjd502.dbo.BOptimalEvent.EventID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOptimalEvent.ObjID
     *
     * @return the value of nfjd502.dbo.BOptimalEvent.ObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getObjid() {
        return objid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOptimalEvent.ObjID
     *
     * @param objid the value for nfjd502.dbo.BOptimalEvent.ObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setObjid(Integer objid) {
        this.objid = objid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOptimalEvent.StartTime
     *
     * @return the value of nfjd502.dbo.BOptimalEvent.StartTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOptimalEvent.StartTime
     *
     * @param starttime the value for nfjd502.dbo.BOptimalEvent.StartTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.BOptimalEvent.EndTime
     *
     * @return the value of nfjd502.dbo.BOptimalEvent.EndTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.BOptimalEvent.EndTime
     *
     * @param endtime the value for nfjd502.dbo.BOptimalEvent.EndTime
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}