package com.wincom.mstar.domain;

public class CAIThreshhold {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.AIObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer aiobjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.ThreshholdNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer threshholdno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.Notify
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Boolean notify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.ThreshholdVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Float threshholdval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.Direction
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.MultiAlarmShield
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Boolean multialarmshield;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.DeadArea
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Float deadarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.NotifyLevel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer notifylevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.UpNotifyNote
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String upnotifynote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.DownNotifyNote
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String downnotifynote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.AlarmRecordEnabled
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Boolean alarmrecordenabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAIThreshhold.CmdList
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String cmdlist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.AIObjID
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.AIObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getAiobjid() {
        return aiobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.AIObjID
     *
     * @param aiobjid the value for nfjd502.dbo.CAIThreshhold.AIObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAiobjid(Integer aiobjid) {
        this.aiobjid = aiobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.ThreshholdNo
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.ThreshholdNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getThreshholdno() {
        return threshholdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.ThreshholdNo
     *
     * @param threshholdno the value for nfjd502.dbo.CAIThreshhold.ThreshholdNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setThreshholdno(Integer threshholdno) {
        this.threshholdno = threshholdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.Notify
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.Notify
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Boolean getNotify() {
        return notify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.Notify
     *
     * @param notify the value for nfjd502.dbo.CAIThreshhold.Notify
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setNotify(Boolean notify) {
        this.notify = notify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.ThreshholdVal
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.ThreshholdVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Float getThreshholdval() {
        return threshholdval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.ThreshholdVal
     *
     * @param threshholdval the value for nfjd502.dbo.CAIThreshhold.ThreshholdVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setThreshholdval(Float threshholdval) {
        this.threshholdval = threshholdval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.Direction
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.Direction
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.Direction
     *
     * @param direction the value for nfjd502.dbo.CAIThreshhold.Direction
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.MultiAlarmShield
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.MultiAlarmShield
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Boolean getMultialarmshield() {
        return multialarmshield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.MultiAlarmShield
     *
     * @param multialarmshield the value for nfjd502.dbo.CAIThreshhold.MultiAlarmShield
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMultialarmshield(Boolean multialarmshield) {
        this.multialarmshield = multialarmshield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.DeadArea
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.DeadArea
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Float getDeadarea() {
        return deadarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.DeadArea
     *
     * @param deadarea the value for nfjd502.dbo.CAIThreshhold.DeadArea
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDeadarea(Float deadarea) {
        this.deadarea = deadarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.NotifyLevel
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.NotifyLevel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getNotifylevel() {
        return notifylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.NotifyLevel
     *
     * @param notifylevel the value for nfjd502.dbo.CAIThreshhold.NotifyLevel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setNotifylevel(Integer notifylevel) {
        this.notifylevel = notifylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.UpNotifyNote
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.UpNotifyNote
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getUpnotifynote() {
        return upnotifynote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.UpNotifyNote
     *
     * @param upnotifynote the value for nfjd502.dbo.CAIThreshhold.UpNotifyNote
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setUpnotifynote(String upnotifynote) {
        this.upnotifynote = upnotifynote == null ? null : upnotifynote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.DownNotifyNote
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.DownNotifyNote
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getDownnotifynote() {
        return downnotifynote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.DownNotifyNote
     *
     * @param downnotifynote the value for nfjd502.dbo.CAIThreshhold.DownNotifyNote
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDownnotifynote(String downnotifynote) {
        this.downnotifynote = downnotifynote == null ? null : downnotifynote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.AlarmRecordEnabled
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.AlarmRecordEnabled
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Boolean getAlarmrecordenabled() {
        return alarmrecordenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.AlarmRecordEnabled
     *
     * @param alarmrecordenabled the value for nfjd502.dbo.CAIThreshhold.AlarmRecordEnabled
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAlarmrecordenabled(Boolean alarmrecordenabled) {
        this.alarmrecordenabled = alarmrecordenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAIThreshhold.CmdList
     *
     * @return the value of nfjd502.dbo.CAIThreshhold.CmdList
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getCmdlist() {
        return cmdlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAIThreshhold.CmdList
     *
     * @param cmdlist the value for nfjd502.dbo.CAIThreshhold.CmdList
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setCmdlist(String cmdlist) {
        this.cmdlist = cmdlist == null ? null : cmdlist.trim();
    }
}