package com.wincom.mstar.domain;

public class CAOObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAOObject.AOObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer aoobjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAOObject.bMaxVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Boolean bmaxval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAOObject.bMinVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Boolean bminval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAOObject.MaxVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Float maxval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAOObject.MinVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Float minval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAOObject.MeasureMonad
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String measuremonad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CAOObject.AIprecision
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Byte aiprecision;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAOObject.AOObjID
     *
     * @return the value of nfjd502.dbo.CAOObject.AOObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getAoobjid() {
        return aoobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAOObject.AOObjID
     *
     * @param aoobjid the value for nfjd502.dbo.CAOObject.AOObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAoobjid(Integer aoobjid) {
        this.aoobjid = aoobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAOObject.bMaxVal
     *
     * @return the value of nfjd502.dbo.CAOObject.bMaxVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Boolean getBmaxval() {
        return bmaxval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAOObject.bMaxVal
     *
     * @param bmaxval the value for nfjd502.dbo.CAOObject.bMaxVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setBmaxval(Boolean bmaxval) {
        this.bmaxval = bmaxval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAOObject.bMinVal
     *
     * @return the value of nfjd502.dbo.CAOObject.bMinVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Boolean getBminval() {
        return bminval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAOObject.bMinVal
     *
     * @param bminval the value for nfjd502.dbo.CAOObject.bMinVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setBminval(Boolean bminval) {
        this.bminval = bminval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAOObject.MaxVal
     *
     * @return the value of nfjd502.dbo.CAOObject.MaxVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Float getMaxval() {
        return maxval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAOObject.MaxVal
     *
     * @param maxval the value for nfjd502.dbo.CAOObject.MaxVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMaxval(Float maxval) {
        this.maxval = maxval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAOObject.MinVal
     *
     * @return the value of nfjd502.dbo.CAOObject.MinVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Float getMinval() {
        return minval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAOObject.MinVal
     *
     * @param minval the value for nfjd502.dbo.CAOObject.MinVal
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMinval(Float minval) {
        this.minval = minval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAOObject.MeasureMonad
     *
     * @return the value of nfjd502.dbo.CAOObject.MeasureMonad
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getMeasuremonad() {
        return measuremonad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAOObject.MeasureMonad
     *
     * @param measuremonad the value for nfjd502.dbo.CAOObject.MeasureMonad
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMeasuremonad(String measuremonad) {
        this.measuremonad = measuremonad == null ? null : measuremonad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CAOObject.AIprecision
     *
     * @return the value of nfjd502.dbo.CAOObject.AIprecision
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Byte getAiprecision() {
        return aiprecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CAOObject.AIprecision
     *
     * @param aiprecision the value for nfjd502.dbo.CAOObject.AIprecision
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAiprecision(Byte aiprecision) {
        this.aiprecision = aiprecision;
    }
}