package com.wincom.mstar.domain;

import java.util.ArrayList;
import java.util.List;

public class CComboOperationObjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public CComboOperationObjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOperationobjidIsNull() {
            addCriterion("OperationObjID is null");
            return (Criteria) this;
        }

        public Criteria andOperationobjidIsNotNull() {
            addCriterion("OperationObjID is not null");
            return (Criteria) this;
        }

        public Criteria andOperationobjidEqualTo(Integer value) {
            addCriterion("OperationObjID =", value, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationobjidNotEqualTo(Integer value) {
            addCriterion("OperationObjID <>", value, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationobjidGreaterThan(Integer value) {
            addCriterion("OperationObjID >", value, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationobjidGreaterThanOrEqualTo(Integer value) {
            addCriterion("OperationObjID >=", value, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationobjidLessThan(Integer value) {
            addCriterion("OperationObjID <", value, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationobjidLessThanOrEqualTo(Integer value) {
            addCriterion("OperationObjID <=", value, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationobjidIn(List<Integer> values) {
            addCriterion("OperationObjID in", values, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationobjidNotIn(List<Integer> values) {
            addCriterion("OperationObjID not in", values, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationobjidBetween(Integer value1, Integer value2) {
            addCriterion("OperationObjID between", value1, value2, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationobjidNotBetween(Integer value1, Integer value2) {
            addCriterion("OperationObjID not between", value1, value2, "operationobjid");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagIsNull() {
            addCriterion("OperationPriorityFlag is null");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagIsNotNull() {
            addCriterion("OperationPriorityFlag is not null");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagEqualTo(Boolean value) {
            addCriterion("OperationPriorityFlag =", value, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagNotEqualTo(Boolean value) {
            addCriterion("OperationPriorityFlag <>", value, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagGreaterThan(Boolean value) {
            addCriterion("OperationPriorityFlag >", value, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("OperationPriorityFlag >=", value, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagLessThan(Boolean value) {
            addCriterion("OperationPriorityFlag <", value, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagLessThanOrEqualTo(Boolean value) {
            addCriterion("OperationPriorityFlag <=", value, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagIn(List<Boolean> values) {
            addCriterion("OperationPriorityFlag in", values, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagNotIn(List<Boolean> values) {
            addCriterion("OperationPriorityFlag not in", values, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagBetween(Boolean value1, Boolean value2) {
            addCriterion("OperationPriorityFlag between", value1, value2, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andOperationpriorityflagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("OperationPriorityFlag not between", value1, value2, "operationpriorityflag");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidIsNull() {
            addCriterion("SuccessConditionID is null");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidIsNotNull() {
            addCriterion("SuccessConditionID is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidEqualTo(Integer value) {
            addCriterion("SuccessConditionID =", value, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidNotEqualTo(Integer value) {
            addCriterion("SuccessConditionID <>", value, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidGreaterThan(Integer value) {
            addCriterion("SuccessConditionID >", value, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SuccessConditionID >=", value, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidLessThan(Integer value) {
            addCriterion("SuccessConditionID <", value, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidLessThanOrEqualTo(Integer value) {
            addCriterion("SuccessConditionID <=", value, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidIn(List<Integer> values) {
            addCriterion("SuccessConditionID in", values, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidNotIn(List<Integer> values) {
            addCriterion("SuccessConditionID not in", values, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidBetween(Integer value1, Integer value2) {
            addCriterion("SuccessConditionID between", value1, value2, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andSuccessconditionidNotBetween(Integer value1, Integer value2) {
            addCriterion("SuccessConditionID not between", value1, value2, "successconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidIsNull() {
            addCriterion("AllowConditionID is null");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidIsNotNull() {
            addCriterion("AllowConditionID is not null");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidEqualTo(Integer value) {
            addCriterion("AllowConditionID =", value, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidNotEqualTo(Integer value) {
            addCriterion("AllowConditionID <>", value, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidGreaterThan(Integer value) {
            addCriterion("AllowConditionID >", value, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidGreaterThanOrEqualTo(Integer value) {
            addCriterion("AllowConditionID >=", value, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidLessThan(Integer value) {
            addCriterion("AllowConditionID <", value, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidLessThanOrEqualTo(Integer value) {
            addCriterion("AllowConditionID <=", value, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidIn(List<Integer> values) {
            addCriterion("AllowConditionID in", values, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidNotIn(List<Integer> values) {
            addCriterion("AllowConditionID not in", values, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidBetween(Integer value1, Integer value2) {
            addCriterion("AllowConditionID between", value1, value2, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andAllowconditionidNotBetween(Integer value1, Integer value2) {
            addCriterion("AllowConditionID not between", value1, value2, "allowconditionid");
            return (Criteria) this;
        }

        public Criteria andDelayIsNull() {
            addCriterion("Delay is null");
            return (Criteria) this;
        }

        public Criteria andDelayIsNotNull() {
            addCriterion("Delay is not null");
            return (Criteria) this;
        }

        public Criteria andDelayEqualTo(Integer value) {
            addCriterion("Delay =", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotEqualTo(Integer value) {
            addCriterion("Delay <>", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayGreaterThan(Integer value) {
            addCriterion("Delay >", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayGreaterThanOrEqualTo(Integer value) {
            addCriterion("Delay >=", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayLessThan(Integer value) {
            addCriterion("Delay <", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayLessThanOrEqualTo(Integer value) {
            addCriterion("Delay <=", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayIn(List<Integer> values) {
            addCriterion("Delay in", values, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotIn(List<Integer> values) {
            addCriterion("Delay not in", values, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayBetween(Integer value1, Integer value2) {
            addCriterion("Delay between", value1, value2, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotBetween(Integer value1, Integer value2) {
            addCriterion("Delay not between", value1, value2, "delay");
            return (Criteria) this;
        }

        public Criteria andRecordenabledIsNull() {
            addCriterion("RecordEnabled is null");
            return (Criteria) this;
        }

        public Criteria andRecordenabledIsNotNull() {
            addCriterion("RecordEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andRecordenabledEqualTo(Boolean value) {
            addCriterion("RecordEnabled =", value, "recordenabled");
            return (Criteria) this;
        }

        public Criteria andRecordenabledNotEqualTo(Boolean value) {
            addCriterion("RecordEnabled <>", value, "recordenabled");
            return (Criteria) this;
        }

        public Criteria andRecordenabledGreaterThan(Boolean value) {
            addCriterion("RecordEnabled >", value, "recordenabled");
            return (Criteria) this;
        }

        public Criteria andRecordenabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("RecordEnabled >=", value, "recordenabled");
            return (Criteria) this;
        }

        public Criteria andRecordenabledLessThan(Boolean value) {
            addCriterion("RecordEnabled <", value, "recordenabled");
            return (Criteria) this;
        }

        public Criteria andRecordenabledLessThanOrEqualTo(Boolean value) {
            addCriterion("RecordEnabled <=", value, "recordenabled");
            return (Criteria) this;
        }

        public Criteria andRecordenabledIn(List<Boolean> values) {
            addCriterion("RecordEnabled in", values, "recordenabled");
            return (Criteria) this;
        }

        public Criteria andRecordenabledNotIn(List<Boolean> values) {
            addCriterion("RecordEnabled not in", values, "recordenabled");
            return (Criteria) this;
        }

        public Criteria andRecordenabledBetween(Boolean value1, Boolean value2) {
            addCriterion("RecordEnabled between", value1, value2, "recordenabled");
            return (Criteria) this;
        }

        public Criteria andRecordenabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("RecordEnabled not between", value1, value2, "recordenabled");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 02 11:23:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nfjd502.dbo.CComboOperationObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}