package com.wincom.mstar.domain;

import java.util.Date;

public class CDevice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDevice.DeviceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDevice.DeviceTypeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer devicetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDevice.ModelID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer modelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDevice.MountPlaceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer mountplaceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDevice.StartUseDate
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date startusedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDevice.ParDeviceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer pardeviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDevice.UseStatus
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Boolean usestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDevice.Rating
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Double rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDevice.DeviceID
     *
     * @return the value of nfjd502.dbo.CDevice.DeviceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDevice.DeviceID
     *
     * @param deviceid the value for nfjd502.dbo.CDevice.DeviceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDeviceid(Integer deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDevice.DeviceTypeID
     *
     * @return the value of nfjd502.dbo.CDevice.DeviceTypeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDevicetypeid() {
        return devicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDevice.DeviceTypeID
     *
     * @param devicetypeid the value for nfjd502.dbo.CDevice.DeviceTypeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDevicetypeid(Integer devicetypeid) {
        this.devicetypeid = devicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDevice.ModelID
     *
     * @return the value of nfjd502.dbo.CDevice.ModelID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDevice.ModelID
     *
     * @param modelid the value for nfjd502.dbo.CDevice.ModelID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setModelid(Integer modelid) {
        this.modelid = modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDevice.MountPlaceID
     *
     * @return the value of nfjd502.dbo.CDevice.MountPlaceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getMountplaceid() {
        return mountplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDevice.MountPlaceID
     *
     * @param mountplaceid the value for nfjd502.dbo.CDevice.MountPlaceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMountplaceid(Integer mountplaceid) {
        this.mountplaceid = mountplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDevice.StartUseDate
     *
     * @return the value of nfjd502.dbo.CDevice.StartUseDate
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getStartusedate() {
        return startusedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDevice.StartUseDate
     *
     * @param startusedate the value for nfjd502.dbo.CDevice.StartUseDate
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setStartusedate(Date startusedate) {
        this.startusedate = startusedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDevice.ParDeviceID
     *
     * @return the value of nfjd502.dbo.CDevice.ParDeviceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getPardeviceid() {
        return pardeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDevice.ParDeviceID
     *
     * @param pardeviceid the value for nfjd502.dbo.CDevice.ParDeviceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setPardeviceid(Integer pardeviceid) {
        this.pardeviceid = pardeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDevice.UseStatus
     *
     * @return the value of nfjd502.dbo.CDevice.UseStatus
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Boolean getUsestatus() {
        return usestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDevice.UseStatus
     *
     * @param usestatus the value for nfjd502.dbo.CDevice.UseStatus
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setUsestatus(Boolean usestatus) {
        this.usestatus = usestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDevice.Rating
     *
     * @return the value of nfjd502.dbo.CDevice.Rating
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Double getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDevice.Rating
     *
     * @param rating the value for nfjd502.dbo.CDevice.Rating
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setRating(Double rating) {
        this.rating = rating;
    }
}