package com.wincom.mstar.domain;

public class CDeviceType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDeviceType.DeviceTypeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer devicetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDeviceType.DeviceTypeAlias
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String devicetypealias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDeviceType.DeviceTypeName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String devicetypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDeviceType.DeviceTypeClass
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer devicetypeclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CDeviceType.DeviceTypeNote
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String devicetypenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeID
     *
     * @return the value of nfjd502.dbo.CDeviceType.DeviceTypeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDevicetypeid() {
        return devicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeID
     *
     * @param devicetypeid the value for nfjd502.dbo.CDeviceType.DeviceTypeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDevicetypeid(Integer devicetypeid) {
        this.devicetypeid = devicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeAlias
     *
     * @return the value of nfjd502.dbo.CDeviceType.DeviceTypeAlias
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getDevicetypealias() {
        return devicetypealias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeAlias
     *
     * @param devicetypealias the value for nfjd502.dbo.CDeviceType.DeviceTypeAlias
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDevicetypealias(String devicetypealias) {
        this.devicetypealias = devicetypealias == null ? null : devicetypealias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeName
     *
     * @return the value of nfjd502.dbo.CDeviceType.DeviceTypeName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getDevicetypename() {
        return devicetypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeName
     *
     * @param devicetypename the value for nfjd502.dbo.CDeviceType.DeviceTypeName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDevicetypename(String devicetypename) {
        this.devicetypename = devicetypename == null ? null : devicetypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeClass
     *
     * @return the value of nfjd502.dbo.CDeviceType.DeviceTypeClass
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDevicetypeclass() {
        return devicetypeclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeClass
     *
     * @param devicetypeclass the value for nfjd502.dbo.CDeviceType.DeviceTypeClass
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDevicetypeclass(Integer devicetypeclass) {
        this.devicetypeclass = devicetypeclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeNote
     *
     * @return the value of nfjd502.dbo.CDeviceType.DeviceTypeNote
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getDevicetypenote() {
        return devicetypenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CDeviceType.DeviceTypeNote
     *
     * @param devicetypenote the value for nfjd502.dbo.CDeviceType.DeviceTypeNote
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDevicetypenote(String devicetypenote) {
        this.devicetypenote = devicetypenote == null ? null : devicetypenote.trim();
    }
}