package com.wincom.mstar.domain;

public class CEmploye {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CEmploye.EmployeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer employeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CEmploye.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CEmploye.SerialID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String serialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CEmploye.tel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CEmploye.address
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CEmploye.CompanyName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CEmploye.EmailBox
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String emailbox;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CEmploye.EmployeID
     *
     * @return the value of nfjd502.dbo.CEmploye.EmployeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getEmployeid() {
        return employeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CEmploye.EmployeID
     *
     * @param employeid the value for nfjd502.dbo.CEmploye.EmployeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setEmployeid(Integer employeid) {
        this.employeid = employeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CEmploye.Name
     *
     * @return the value of nfjd502.dbo.CEmploye.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CEmploye.Name
     *
     * @param name the value for nfjd502.dbo.CEmploye.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CEmploye.SerialID
     *
     * @return the value of nfjd502.dbo.CEmploye.SerialID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getSerialid() {
        return serialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CEmploye.SerialID
     *
     * @param serialid the value for nfjd502.dbo.CEmploye.SerialID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setSerialid(String serialid) {
        this.serialid = serialid == null ? null : serialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CEmploye.tel
     *
     * @return the value of nfjd502.dbo.CEmploye.tel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CEmploye.tel
     *
     * @param tel the value for nfjd502.dbo.CEmploye.tel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CEmploye.address
     *
     * @return the value of nfjd502.dbo.CEmploye.address
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CEmploye.address
     *
     * @param address the value for nfjd502.dbo.CEmploye.address
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CEmploye.CompanyName
     *
     * @return the value of nfjd502.dbo.CEmploye.CompanyName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CEmploye.CompanyName
     *
     * @param companyname the value for nfjd502.dbo.CEmploye.CompanyName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CEmploye.EmailBox
     *
     * @return the value of nfjd502.dbo.CEmploye.EmailBox
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getEmailbox() {
        return emailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CEmploye.EmailBox
     *
     * @param emailbox the value for nfjd502.dbo.CEmploye.EmailBox
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setEmailbox(String emailbox) {
        this.emailbox = emailbox == null ? null : emailbox.trim();
    }
}