package com.wincom.mstar.domain;

public class CKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CKey.KeyID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String keyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CKey.UserName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CKey.KeyID
     *
     * @return the value of nfjd502.dbo.CKey.KeyID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CKey.KeyID
     *
     * @param keyid the value for nfjd502.dbo.CKey.KeyID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setKeyid(String keyid) {
        this.keyid = keyid == null ? null : keyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CKey.UserName
     *
     * @return the value of nfjd502.dbo.CKey.UserName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CKey.UserName
     *
     * @param username the value for nfjd502.dbo.CKey.UserName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}