package com.wincom.mstar.domain;

import java.util.ArrayList;
import java.util.List;

public class CLogicalObjPosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public CLogicalObjPosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andObjidIsNull() {
            addCriterion("ObjID is null");
            return (Criteria) this;
        }

        public Criteria andObjidIsNotNull() {
            addCriterion("ObjID is not null");
            return (Criteria) this;
        }

        public Criteria andObjidEqualTo(Integer value) {
            addCriterion("ObjID =", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidNotEqualTo(Integer value) {
            addCriterion("ObjID <>", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidGreaterThan(Integer value) {
            addCriterion("ObjID >", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ObjID >=", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidLessThan(Integer value) {
            addCriterion("ObjID <", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidLessThanOrEqualTo(Integer value) {
            addCriterion("ObjID <=", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidIn(List<Integer> values) {
            addCriterion("ObjID in", values, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidNotIn(List<Integer> values) {
            addCriterion("ObjID not in", values, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidBetween(Integer value1, Integer value2) {
            addCriterion("ObjID between", value1, value2, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidNotBetween(Integer value1, Integer value2) {
            addCriterion("ObjID not between", value1, value2, "objid");
            return (Criteria) this;
        }

        public Criteria andFeatureidIsNull() {
            addCriterion("FeatureID is null");
            return (Criteria) this;
        }

        public Criteria andFeatureidIsNotNull() {
            addCriterion("FeatureID is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureidEqualTo(Integer value) {
            addCriterion("FeatureID =", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidNotEqualTo(Integer value) {
            addCriterion("FeatureID <>", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidGreaterThan(Integer value) {
            addCriterion("FeatureID >", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidGreaterThanOrEqualTo(Integer value) {
            addCriterion("FeatureID >=", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidLessThan(Integer value) {
            addCriterion("FeatureID <", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidLessThanOrEqualTo(Integer value) {
            addCriterion("FeatureID <=", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidIn(List<Integer> values) {
            addCriterion("FeatureID in", values, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidNotIn(List<Integer> values) {
            addCriterion("FeatureID not in", values, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidBetween(Integer value1, Integer value2) {
            addCriterion("FeatureID between", value1, value2, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidNotBetween(Integer value1, Integer value2) {
            addCriterion("FeatureID not between", value1, value2, "featureid");
            return (Criteria) this;
        }

        public Criteria andXIsNull() {
            addCriterion("X is null");
            return (Criteria) this;
        }

        public Criteria andXIsNotNull() {
            addCriterion("X is not null");
            return (Criteria) this;
        }

        public Criteria andXEqualTo(Double value) {
            addCriterion("X =", value, "x");
            return (Criteria) this;
        }

        public Criteria andXNotEqualTo(Double value) {
            addCriterion("X <>", value, "x");
            return (Criteria) this;
        }

        public Criteria andXGreaterThan(Double value) {
            addCriterion("X >", value, "x");
            return (Criteria) this;
        }

        public Criteria andXGreaterThanOrEqualTo(Double value) {
            addCriterion("X >=", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLessThan(Double value) {
            addCriterion("X <", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLessThanOrEqualTo(Double value) {
            addCriterion("X <=", value, "x");
            return (Criteria) this;
        }

        public Criteria andXIn(List<Double> values) {
            addCriterion("X in", values, "x");
            return (Criteria) this;
        }

        public Criteria andXNotIn(List<Double> values) {
            addCriterion("X not in", values, "x");
            return (Criteria) this;
        }

        public Criteria andXBetween(Double value1, Double value2) {
            addCriterion("X between", value1, value2, "x");
            return (Criteria) this;
        }

        public Criteria andXNotBetween(Double value1, Double value2) {
            addCriterion("X not between", value1, value2, "x");
            return (Criteria) this;
        }

        public Criteria andYIsNull() {
            addCriterion("Y is null");
            return (Criteria) this;
        }

        public Criteria andYIsNotNull() {
            addCriterion("Y is not null");
            return (Criteria) this;
        }

        public Criteria andYEqualTo(Double value) {
            addCriterion("Y =", value, "y");
            return (Criteria) this;
        }

        public Criteria andYNotEqualTo(Double value) {
            addCriterion("Y <>", value, "y");
            return (Criteria) this;
        }

        public Criteria andYGreaterThan(Double value) {
            addCriterion("Y >", value, "y");
            return (Criteria) this;
        }

        public Criteria andYGreaterThanOrEqualTo(Double value) {
            addCriterion("Y >=", value, "y");
            return (Criteria) this;
        }

        public Criteria andYLessThan(Double value) {
            addCriterion("Y <", value, "y");
            return (Criteria) this;
        }

        public Criteria andYLessThanOrEqualTo(Double value) {
            addCriterion("Y <=", value, "y");
            return (Criteria) this;
        }

        public Criteria andYIn(List<Double> values) {
            addCriterion("Y in", values, "y");
            return (Criteria) this;
        }

        public Criteria andYNotIn(List<Double> values) {
            addCriterion("Y not in", values, "y");
            return (Criteria) this;
        }

        public Criteria andYBetween(Double value1, Double value2) {
            addCriterion("Y between", value1, value2, "y");
            return (Criteria) this;
        }

        public Criteria andYNotBetween(Double value1, Double value2) {
            addCriterion("Y not between", value1, value2, "y");
            return (Criteria) this;
        }

        public Criteria andLayornameIsNull() {
            addCriterion("LayorName is null");
            return (Criteria) this;
        }

        public Criteria andLayornameIsNotNull() {
            addCriterion("LayorName is not null");
            return (Criteria) this;
        }

        public Criteria andLayornameEqualTo(String value) {
            addCriterion("LayorName =", value, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameNotEqualTo(String value) {
            addCriterion("LayorName <>", value, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameGreaterThan(String value) {
            addCriterion("LayorName >", value, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameGreaterThanOrEqualTo(String value) {
            addCriterion("LayorName >=", value, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameLessThan(String value) {
            addCriterion("LayorName <", value, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameLessThanOrEqualTo(String value) {
            addCriterion("LayorName <=", value, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameLike(String value) {
            addCriterion("LayorName like", value, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameNotLike(String value) {
            addCriterion("LayorName not like", value, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameIn(List<String> values) {
            addCriterion("LayorName in", values, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameNotIn(List<String> values) {
            addCriterion("LayorName not in", values, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameBetween(String value1, String value2) {
            addCriterion("LayorName between", value1, value2, "layorname");
            return (Criteria) this;
        }

        public Criteria andLayornameNotBetween(String value1, String value2) {
            addCriterion("LayorName not between", value1, value2, "layorname");
            return (Criteria) this;
        }

        public Criteria andBmpfileIsNull() {
            addCriterion("BmpFile is null");
            return (Criteria) this;
        }

        public Criteria andBmpfileIsNotNull() {
            addCriterion("BmpFile is not null");
            return (Criteria) this;
        }

        public Criteria andBmpfileEqualTo(String value) {
            addCriterion("BmpFile =", value, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileNotEqualTo(String value) {
            addCriterion("BmpFile <>", value, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileGreaterThan(String value) {
            addCriterion("BmpFile >", value, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileGreaterThanOrEqualTo(String value) {
            addCriterion("BmpFile >=", value, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileLessThan(String value) {
            addCriterion("BmpFile <", value, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileLessThanOrEqualTo(String value) {
            addCriterion("BmpFile <=", value, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileLike(String value) {
            addCriterion("BmpFile like", value, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileNotLike(String value) {
            addCriterion("BmpFile not like", value, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileIn(List<String> values) {
            addCriterion("BmpFile in", values, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileNotIn(List<String> values) {
            addCriterion("BmpFile not in", values, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileBetween(String value1, String value2) {
            addCriterion("BmpFile between", value1, value2, "bmpfile");
            return (Criteria) this;
        }

        public Criteria andBmpfileNotBetween(String value1, String value2) {
            addCriterion("BmpFile not between", value1, value2, "bmpfile");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 02 11:23:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nfjd502.dbo.CLogicalObjPos
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}