package com.wincom.mstar.domain;

public class CModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CModel.ModelID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer modelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CModel.DeviceTypeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer devicetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CModel.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CModel.Category
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CModel.MountPlaceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer mountplaceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CModel.SpanYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer spanyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CModel.Notes
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CModel.ModelID
     *
     * @return the value of nfjd502.dbo.CModel.ModelID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CModel.ModelID
     *
     * @param modelid the value for nfjd502.dbo.CModel.ModelID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setModelid(Integer modelid) {
        this.modelid = modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CModel.DeviceTypeID
     *
     * @return the value of nfjd502.dbo.CModel.DeviceTypeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDevicetypeid() {
        return devicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CModel.DeviceTypeID
     *
     * @param devicetypeid the value for nfjd502.dbo.CModel.DeviceTypeID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDevicetypeid(Integer devicetypeid) {
        this.devicetypeid = devicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CModel.Name
     *
     * @return the value of nfjd502.dbo.CModel.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CModel.Name
     *
     * @param name the value for nfjd502.dbo.CModel.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CModel.Category
     *
     * @return the value of nfjd502.dbo.CModel.Category
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CModel.Category
     *
     * @param category the value for nfjd502.dbo.CModel.Category
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CModel.MountPlaceID
     *
     * @return the value of nfjd502.dbo.CModel.MountPlaceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getMountplaceid() {
        return mountplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CModel.MountPlaceID
     *
     * @param mountplaceid the value for nfjd502.dbo.CModel.MountPlaceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMountplaceid(Integer mountplaceid) {
        this.mountplaceid = mountplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CModel.SpanYear
     *
     * @return the value of nfjd502.dbo.CModel.SpanYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getSpanyear() {
        return spanyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CModel.SpanYear
     *
     * @param spanyear the value for nfjd502.dbo.CModel.SpanYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setSpanyear(Integer spanyear) {
        this.spanyear = spanyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CModel.Notes
     *
     * @return the value of nfjd502.dbo.CModel.Notes
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CModel.Notes
     *
     * @param notes the value for nfjd502.dbo.CModel.Notes
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}