package com.wincom.mstar.domain;

public class CMountPlace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CMountPlace.MountPlaceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer mountplaceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CMountPlace.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CMountPlace.Contact
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CMountPlace.Tel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CMountPlace.Fax
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CMountPlace.Addr
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CMountPlace.Notes
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CMountPlace.MountPlaceID
     *
     * @return the value of nfjd502.dbo.CMountPlace.MountPlaceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getMountplaceid() {
        return mountplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CMountPlace.MountPlaceID
     *
     * @param mountplaceid the value for nfjd502.dbo.CMountPlace.MountPlaceID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setMountplaceid(Integer mountplaceid) {
        this.mountplaceid = mountplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CMountPlace.Name
     *
     * @return the value of nfjd502.dbo.CMountPlace.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CMountPlace.Name
     *
     * @param name the value for nfjd502.dbo.CMountPlace.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CMountPlace.Contact
     *
     * @return the value of nfjd502.dbo.CMountPlace.Contact
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CMountPlace.Contact
     *
     * @param contact the value for nfjd502.dbo.CMountPlace.Contact
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CMountPlace.Tel
     *
     * @return the value of nfjd502.dbo.CMountPlace.Tel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CMountPlace.Tel
     *
     * @param tel the value for nfjd502.dbo.CMountPlace.Tel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CMountPlace.Fax
     *
     * @return the value of nfjd502.dbo.CMountPlace.Fax
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CMountPlace.Fax
     *
     * @param fax the value for nfjd502.dbo.CMountPlace.Fax
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CMountPlace.Addr
     *
     * @return the value of nfjd502.dbo.CMountPlace.Addr
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CMountPlace.Addr
     *
     * @param addr the value for nfjd502.dbo.CMountPlace.Addr
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CMountPlace.Notes
     *
     * @return the value of nfjd502.dbo.CMountPlace.Notes
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CMountPlace.Notes
     *
     * @param notes the value for nfjd502.dbo.CMountPlace.Notes
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}