package com.wincom.mstar.domain;

public class CStationProperty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CStationProperty.ObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer objid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CStationProperty.StationType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer stationtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CStationProperty.ObjID
     *
     * @return the value of nfjd502.dbo.CStationProperty.ObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getObjid() {
        return objid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CStationProperty.ObjID
     *
     * @param objid the value for nfjd502.dbo.CStationProperty.ObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setObjid(Integer objid) {
        this.objid = objid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CStationProperty.StationType
     *
     * @return the value of nfjd502.dbo.CStationProperty.StationType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getStationtype() {
        return stationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CStationProperty.StationType
     *
     * @param stationtype the value for nfjd502.dbo.CStationProperty.StationType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setStationtype(Integer stationtype) {
        this.stationtype = stationtype;
    }
}