package com.wincom.mstar.domain;

public class CZNotifyLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CZNotifyLevel.NotifyLevel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer notifylevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.CZNotifyLevel.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CZNotifyLevel.NotifyLevel
     *
     * @return the value of nfjd502.dbo.CZNotifyLevel.NotifyLevel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getNotifylevel() {
        return notifylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CZNotifyLevel.NotifyLevel
     *
     * @param notifylevel the value for nfjd502.dbo.CZNotifyLevel.NotifyLevel
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setNotifylevel(Integer notifylevel) {
        this.notifylevel = notifylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.CZNotifyLevel.Name
     *
     * @return the value of nfjd502.dbo.CZNotifyLevel.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.CZNotifyLevel.Name
     *
     * @param name the value for nfjd502.dbo.CZNotifyLevel.Name
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}