package com.wincom.mstar.domain;

import java.util.Date;

public class View_DeviceProperty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.LogObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer logobjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.FullName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.LogObjAlias
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String logobjalias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.LogObjName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String logobjname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.DeviceProducer
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String deviceproducer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.DeviceVersion
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String deviceversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.UseDate
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Date usedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.DeviceType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer devicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.DeviceNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String deviceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.DeviceName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String devicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.LogObjType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer logobjtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.ParLogObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer parlogobjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.DataObjName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private String dataobjname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nfjd502.dbo.View_DeviceProperty.DataObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    private Integer dataobjid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.LogObjID
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.LogObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getLogobjid() {
        return logobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.LogObjID
     *
     * @param logobjid the value for nfjd502.dbo.View_DeviceProperty.LogObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setLogobjid(Integer logobjid) {
        this.logobjid = logobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.FullName
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.FullName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.FullName
     *
     * @param fullname the value for nfjd502.dbo.View_DeviceProperty.FullName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.LogObjAlias
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.LogObjAlias
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getLogobjalias() {
        return logobjalias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.LogObjAlias
     *
     * @param logobjalias the value for nfjd502.dbo.View_DeviceProperty.LogObjAlias
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setLogobjalias(String logobjalias) {
        this.logobjalias = logobjalias == null ? null : logobjalias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.LogObjName
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.LogObjName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getLogobjname() {
        return logobjname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.LogObjName
     *
     * @param logobjname the value for nfjd502.dbo.View_DeviceProperty.LogObjName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setLogobjname(String logobjname) {
        this.logobjname = logobjname == null ? null : logobjname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceProducer
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.DeviceProducer
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getDeviceproducer() {
        return deviceproducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceProducer
     *
     * @param deviceproducer the value for nfjd502.dbo.View_DeviceProperty.DeviceProducer
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDeviceproducer(String deviceproducer) {
        this.deviceproducer = deviceproducer == null ? null : deviceproducer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceVersion
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.DeviceVersion
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getDeviceversion() {
        return deviceversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceVersion
     *
     * @param deviceversion the value for nfjd502.dbo.View_DeviceProperty.DeviceVersion
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDeviceversion(String deviceversion) {
        this.deviceversion = deviceversion == null ? null : deviceversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.UseDate
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.UseDate
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Date getUsedate() {
        return usedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.UseDate
     *
     * @param usedate the value for nfjd502.dbo.View_DeviceProperty.UseDate
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setUsedate(Date usedate) {
        this.usedate = usedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceType
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.DeviceType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceType
     *
     * @param devicetype the value for nfjd502.dbo.View_DeviceProperty.DeviceType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDevicetype(Integer devicetype) {
        this.devicetype = devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceNo
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.DeviceNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getDeviceno() {
        return deviceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceNo
     *
     * @param deviceno the value for nfjd502.dbo.View_DeviceProperty.DeviceNo
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDeviceno(String deviceno) {
        this.deviceno = deviceno == null ? null : deviceno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceName
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.DeviceName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getDevicename() {
        return devicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.DeviceName
     *
     * @param devicename the value for nfjd502.dbo.View_DeviceProperty.DeviceName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDevicename(String devicename) {
        this.devicename = devicename == null ? null : devicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.LogObjType
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.LogObjType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getLogobjtype() {
        return logobjtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.LogObjType
     *
     * @param logobjtype the value for nfjd502.dbo.View_DeviceProperty.LogObjType
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setLogobjtype(Integer logobjtype) {
        this.logobjtype = logobjtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.ParLogObjID
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.ParLogObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getParlogobjid() {
        return parlogobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.ParLogObjID
     *
     * @param parlogobjid the value for nfjd502.dbo.View_DeviceProperty.ParLogObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setParlogobjid(Integer parlogobjid) {
        this.parlogobjid = parlogobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.DataObjName
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.DataObjName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public String getDataobjname() {
        return dataobjname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.DataObjName
     *
     * @param dataobjname the value for nfjd502.dbo.View_DeviceProperty.DataObjName
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDataobjname(String dataobjname) {
        this.dataobjname = dataobjname == null ? null : dataobjname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nfjd502.dbo.View_DeviceProperty.DataObjID
     *
     * @return the value of nfjd502.dbo.View_DeviceProperty.DataObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public Integer getDataobjid() {
        return dataobjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nfjd502.dbo.View_DeviceProperty.DataObjID
     *
     * @param dataobjid the value for nfjd502.dbo.View_DeviceProperty.DataObjID
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    public void setDataobjid(Integer dataobjid) {
        this.dataobjid = dataobjid;
    }
}