package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.BAlarmData;
import com.wincom.mstar.domain.BAlarmDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BAlarmDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BAlarmData
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(BAlarmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BAlarmData
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(BAlarmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BAlarmData
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(BAlarmData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BAlarmData
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(BAlarmData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BAlarmData
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<BAlarmData> selectByExampleWithBLOBs(BAlarmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BAlarmData
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<BAlarmData> selectByExample(BAlarmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BAlarmData
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") BAlarmData record, @Param("example") BAlarmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BAlarmData
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") BAlarmData record, @Param("example") BAlarmDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BAlarmData
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") BAlarmData record, @Param("example") BAlarmDataExample example);
}