package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.BEnergyYear;
import com.wincom.mstar.domain.BEnergyYearExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BEnergyYearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(BEnergyYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(BEnergyYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(BEnergyYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(BEnergyYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<BEnergyYear> selectByExample(BEnergyYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") BEnergyYear record, @Param("example") BEnergyYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyYear
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") BEnergyYear record, @Param("example") BEnergyYearExample example);
}