package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.BEnergyHour;
import com.wincom.mstar.domain.BEnergyHourExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BEnergyHourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyHour
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(BEnergyHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyHour
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(BEnergyHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyHour
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(BEnergyHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyHour
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(BEnergyHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyHour
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<BEnergyHour> selectByExample(BEnergyHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyHour
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") BEnergyHour record, @Param("example") BEnergyHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.BEnergyHour
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") BEnergyHour record, @Param("example") BEnergyHourExample example);
}