package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.BOperationLog;
import com.wincom.mstar.domain.BOperationLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOperationLog
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(BOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOperationLog
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(BOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOperationLog
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(BOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOperationLog
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(BOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOperationLog
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<BOperationLog> selectByExample(BOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOperationLog
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") BOperationLog record, @Param("example") BOperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOperationLog
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") BOperationLog record, @Param("example") BOperationLogExample example);
}