package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.BOptimalEvent;
import com.wincom.mstar.domain.BOptimalEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BOptimalEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOptimalEvent
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(BOptimalEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOptimalEvent
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(BOptimalEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOptimalEvent
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(BOptimalEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOptimalEvent
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(BOptimalEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOptimalEvent
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<BOptimalEvent> selectByExample(BOptimalEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOptimalEvent
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") BOptimalEvent record, @Param("example") BOptimalEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.BOptimalEvent
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") BOptimalEvent record, @Param("example") BOptimalEventExample example);
}