package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.CAIObject;
import com.wincom.mstar.domain.CAIObjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CAIObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(CAIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(CAIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(CAIObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(CAIObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CAIObject> selectByExampleWithBLOBs(CAIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CAIObject> selectByExample(CAIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") CAIObject record, @Param("example") CAIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CAIObject record, @Param("example") CAIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") CAIObject record, @Param("example") CAIObjectExample example);
}