package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.CAIThreshhold;
import com.wincom.mstar.domain.CAIThreshholdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CAIThreshholdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIThreshhold
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(CAIThreshholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIThreshhold
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(CAIThreshholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIThreshhold
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(CAIThreshhold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIThreshhold
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(CAIThreshhold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIThreshhold
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CAIThreshhold> selectByExample(CAIThreshholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIThreshhold
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") CAIThreshhold record, @Param("example") CAIThreshholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CAIThreshhold
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") CAIThreshhold record, @Param("example") CAIThreshholdExample example);
}