package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.CDataObject;
import com.wincom.mstar.domain.CDataObjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CDataObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDataObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(CDataObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDataObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(CDataObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDataObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(CDataObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDataObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(CDataObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDataObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CDataObject> selectByExampleWithBLOBs(CDataObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDataObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CDataObject> selectByExample(CDataObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDataObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") CDataObject record, @Param("example") CDataObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDataObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CDataObject record, @Param("example") CDataObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDataObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") CDataObject record, @Param("example") CDataObjectExample example);
}