package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.CDIObject;
import com.wincom.mstar.domain.CDIObjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CDIObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(CDIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(CDIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(CDIObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(CDIObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CDIObject> selectByExampleWithBLOBs(CDIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CDIObject> selectByExample(CDIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") CDIObject record, @Param("example") CDIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CDIObject record, @Param("example") CDIObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CDIObject
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") CDIObject record, @Param("example") CDIObjectExample example);
}