package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.CFSUCfg;
import com.wincom.mstar.domain.CFSUCfgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CFSUCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CFSUCfg
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(CFSUCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CFSUCfg
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(CFSUCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CFSUCfg
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(CFSUCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CFSUCfg
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(CFSUCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CFSUCfg
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CFSUCfg> selectByExample(CFSUCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CFSUCfg
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") CFSUCfg record, @Param("example") CFSUCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CFSUCfg
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") CFSUCfg record, @Param("example") CFSUCfgExample example);
}