package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.CLogObjUI;
import com.wincom.mstar.domain.CLogObjUIExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CLogObjUIMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogObjUI
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(CLogObjUIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogObjUI
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(CLogObjUIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogObjUI
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(CLogObjUI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogObjUI
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(CLogObjUI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogObjUI
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CLogObjUI> selectByExampleWithBLOBs(CLogObjUIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogObjUI
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<CLogObjUI> selectByExample(CLogObjUIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogObjUI
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") CLogObjUI record, @Param("example") CLogObjUIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogObjUI
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CLogObjUI record, @Param("example") CLogObjUIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.CLogObjUI
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") CLogObjUI record, @Param("example") CLogObjUIExample example);
}