package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.COperationResultCode;
import com.wincom.mstar.domain.COperationResultCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface COperationResultCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.COperationResultCode
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(COperationResultCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.COperationResultCode
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(COperationResultCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.COperationResultCode
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(COperationResultCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.COperationResultCode
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(COperationResultCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.COperationResultCode
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<COperationResultCode> selectByExample(COperationResultCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.COperationResultCode
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") COperationResultCode record, @Param("example") COperationResultCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.COperationResultCode
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") COperationResultCode record, @Param("example") COperationResultCodeExample example);
}