package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.data_object_view_path;
import com.wincom.mstar.domain.data_object_view_pathExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface data_object_view_pathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.data_object_view_path
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(data_object_view_pathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.data_object_view_path
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(data_object_view_pathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.data_object_view_path
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(data_object_view_path record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.data_object_view_path
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(data_object_view_path record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.data_object_view_path
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<data_object_view_path> selectByExample(data_object_view_pathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.data_object_view_path
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") data_object_view_path record, @Param("example") data_object_view_pathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.data_object_view_path
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") data_object_view_path record, @Param("example") data_object_view_pathExample example);
}