package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.RoleModule;
import com.wincom.mstar.domain.RoleModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.RoleModule
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.RoleModule
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.RoleModule
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(RoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.RoleModule
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(RoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.RoleModule
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<RoleModule> selectByExample(RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.RoleModule
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") RoleModule record, @Param("example") RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nfjd502.dbo.RoleModule
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") RoleModule record, @Param("example") RoleModuleExample example);
}