package com.wincom.mstar.dao.mapper;

import com.wincom.mstar.domain.sysdiagrams;
import com.wincom.mstar.domain.sysdiagramsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysdiagramsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int countByExample(sysdiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByExample(sysdiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int deleteByPrimaryKey(Integer diagramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insert(sysdiagrams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int insertSelective(sysdiagrams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<sysdiagrams> selectByExampleWithBLOBs(sysdiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    List<sysdiagrams> selectByExample(sysdiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    sysdiagrams selectByPrimaryKey(Integer diagramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") sysdiagrams record, @Param("example") sysdiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") sysdiagrams record, @Param("example") sysdiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByExample(@Param("record") sysdiagrams record, @Param("example") sysdiagramsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByPrimaryKeySelective(sysdiagrams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(sysdiagrams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Energy.dbo.sysdiagrams
     *
     * @mbggenerated Thu Mar 02 11:23:21 CST 2017
     */
    int updateByPrimaryKey(sysdiagrams record);
}