insert into history_ai_minute(id, ts, value) values (1, toTimestamp(now()), 1.1);
insert into history_ai_minute(id, ts, value) values (2, toTimestamp(now()), 1.1);
insert into history_ai_minute(id, ts, value) values (3, toTimestamp(now()), 1.1);
insert into history_ai_minute(id, ts, value) values (5, toTimestamp(now()), 1.1);

insert into history_ai_quarter(id, ts, value) values (1, toTimestamp(now()), 1.1);
insert into history_ai_quarter(id, ts, value) values (2, toTimestamp(now()), 1.1);
insert into history_ai_quarter(id, ts, value) values (3, toTimestamp(now()), 1.1);
insert into history_ai_quarter(id, ts, value) values (5, toTimestamp(now()), 1.1);

insert into history_ai_hour(id, ts, value) values (1, toTimestamp(now()), 1.1);
insert into history_ai_hour(id, ts, value) values (2, toTimestamp(now()), 1.1);
insert into history_ai_hour(id, ts, value) values (3, toTimestamp(now()), 1.1);
insert into history_ai_hour(id, ts, value) values (5, toTimestamp(now()), 1.1);

insert into history_ai_day(id, ts, value) values (1, toTimestamp(now()), 1.1);
insert into history_ai_day(id, ts, value) values (2, toTimestamp(now()), 1.1);
insert into history_ai_day(id, ts, value) values (3, toTimestamp(now()), 1.1);
insert into history_ai_day(id, ts, value) values (5, toTimestamp(now()), 1.1);

insert into history_ai_month(id, ts, value) values (1, toTimestamp(now()), 1.1);
insert into history_ai_month(id, ts, value) values (2, toTimestamp(now()), 1.1);
insert into history_ai_month(id, ts, value) values (3, toTimestamp(now()), 1.1);
insert into history_ai_month(id, ts, value) values (5, toTimestamp(now()), 1.1);

insert into history_ai_year(id, ts, value) values (1, toTimestamp(now()), 1.1);
insert into history_ai_year(id, ts, value) values (2, toTimestamp(now()), 1.1);
insert into history_ai_year(id, ts, value) values (3, toTimestamp(now()), 1.1);
insert into history_ai_year(id, ts, value) values (5, toTimestamp(now()), 1.1);
